--
-- PostgreSQL database dump
--

\restrict UHhHpbeBMUOgYi1Hywpda9so9Uc4BrDl7ZdjjQ2nwcrgHhHcX90uHDPDnciocyV

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: handle_updated_at(); Type: FUNCTION; Schema: public; Owner: curator_app
--

CREATE FUNCTION public.handle_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION public.handle_updated_at() OWNER TO curator_app;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cities; Type: TABLE; Schema: public; Owner: curator_app
--

CREATE TABLE public.cities (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    city character varying(255),
    admin_name character varying(255),
    country character varying(255),
    geography public.geography(Point,4326)
);


ALTER TABLE public.cities OWNER TO curator_app;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: curator_app
--

CREATE SEQUENCE public.cities_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cities_id_seq OWNER TO curator_app;

--
-- Name: cities_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: curator_app
--

ALTER SEQUENCE public.cities_id_seq OWNED BY public.cities.id;


--
-- Name: migrations; Type: TABLE; Schema: public; Owner: curator_app
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    hash character varying(40) NOT NULL,
    executed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.migrations OWNER TO curator_app;

--
-- Name: playlist_jobs; Type: TABLE; Schema: public; Owner: curator_app
--

CREATE TABLE public.playlist_jobs (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    search_city text NOT NULL,
    search_date date NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL,
    number_of_songs integer DEFAULT 2 NOT NULL,
    playlist_id text,
    error_message text,
    excluded_genres text[]
);


ALTER TABLE public.playlist_jobs OWNER TO curator_app;

--
-- Name: playlist_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: curator_app
--

ALTER TABLE public.playlist_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.playlist_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cities id; Type: DEFAULT; Schema: public; Owner: curator_app
--

ALTER TABLE ONLY public.cities ALTER COLUMN id SET DEFAULT nextval('public.cities_id_seq'::regclass);


--
-- Name: cities cities_name_unique; Type: CONSTRAINT; Schema: public; Owner: curator_app
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_name_unique UNIQUE (name);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: curator_app
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: migrations migrations_name_key; Type: CONSTRAINT; Schema: public; Owner: curator_app
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_name_key UNIQUE (name);


--
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: curator_app
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- Name: playlist_jobs playlist_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: curator_app
--

ALTER TABLE ONLY public.playlist_jobs
    ADD CONSTRAINT playlist_jobs_pkey PRIMARY KEY (id);


--
-- Name: idx_cities_geography; Type: INDEX; Schema: public; Owner: curator_app
--

CREATE INDEX idx_cities_geography ON public.cities USING gist (geography);


--
-- Name: idx_cities_name_trgm; Type: INDEX; Schema: public; Owner: curator_app
--

CREATE INDEX idx_cities_name_trgm ON public.cities USING gin (name public.gin_trgm_ops);


--
-- Name: idx_jobs_status_created_at; Type: INDEX; Schema: public; Owner: curator_app
--

CREATE INDEX idx_jobs_status_created_at ON public.playlist_jobs USING btree (status, created_at);


--
-- Name: playlist_jobs on_job_update; Type: TRIGGER; Schema: public; Owner: curator_app
--

CREATE TRIGGER on_job_update BEFORE UPDATE ON public.playlist_jobs FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO curator_app;


--
-- PostgreSQL database dump complete
--

\unrestrict UHhHpbeBMUOgYi1Hywpda9so9Uc4BrDl7ZdjjQ2nwcrgHhHcX90uHDPDnciocyV

