CREATE TABLE public.playlist_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- 'pending', 'building', 'complete', 'failed'
  status TEXT DEFAULT 'pending' NOT NULL,
  
  -- Job Inputs
  search_city TEXT NOT NULL,
  search_date DATE NOT NULL,
  latitude NUMERIC(9, 6) NOT NULL,
  longitude NUMERIC(9, 6) NOT NULL,
  number_of_songs INTEGER DEFAULT 2 NOT NULL,
  
  -- Job Outputs
  playlist_id TEXT,
  error_message TEXT
);

-- This function automatically updates the 'updated_at' column
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- This trigger applies the function to our new table
CREATE TRIGGER on_job_update
  BEFORE UPDATE ON public.playlist_jobs
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();