-- Purpose: Create a permanent table for user-saved playlists.
-- This decouples the "User Library" from the ephemeral "Job History".

CREATE TABLE saved_playlists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- The User who owns this playlist (Cascade delete if user deletes account)
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  
  -- Reference to the original job (Optional, for debugging lineage)
  original_job_id BIGINT REFERENCES playlist_jobs(id) ON DELETE SET NULL,
  
  -- Core Metadata
  spotify_playlist_id TEXT NOT NULL,
  name TEXT NOT NULL,       -- e.g. "Austin 12-31-2025 live music"
  city_name TEXT NOT NULL,  -- e.g. "Austin, TX"
  playlist_date DATE NOT NULL,
  
  -- We store the exact event data visible at the time of creation.
  events_snapshot JSONB DEFAULT '[]' NOT NULL,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast retrieval of "My Playlists"
CREATE INDEX idx_saved_playlists_user ON saved_playlists(user_id);