-- Purpose: Create table to store user feedback (bugs, feature requests, design suggestions, etc.)
-- This allows us to:
-- 1. Track all feedback for analytics and prioritization
-- 2. Store feedback with user context (if logged in)
-- 3. Enable future admin dashboard for managing feedback
-- 4. Track resolution status

CREATE TABLE user_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- User Information (optional - anonymous users can submit)
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  user_email TEXT, -- Optional email from form (even if not logged in)
  
  -- Feedback Content
  feedback_type TEXT, -- 'bug', 'feature', 'design', 'general', NULL
  message TEXT NOT NULL, -- The actual feedback text (max 1000 chars, enforced in application)
  
  -- Metadata
  user_agent TEXT, -- Browser/device info for bug reports
  page_url TEXT, -- URL where feedback was submitted
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Admin Fields (for future use)
  status TEXT DEFAULT 'new', -- 'new', 'reviewed', 'resolved', 'archived'
  admin_notes TEXT,
  resolved_at TIMESTAMPTZ
);

-- Indexes for efficient querying
CREATE INDEX idx_user_feedback_created_at ON user_feedback(created_at DESC);
CREATE INDEX idx_user_feedback_status ON user_feedback(status);
CREATE INDEX idx_user_feedback_user_id ON user_feedback(user_id);
CREATE INDEX idx_user_feedback_type ON user_feedback(feedback_type);
